name: Предложить функцию
description: Новая настройка, устройство или улучшение текущей работы
title: "[Идея]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Что хотите настроить или исправить?
      description: Укажите устройство и текущую проблему
    validations:
      required: true
  - type: textarea
    attributes:
      label: Как это должно работать?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Технические данные
      description: Hardware ID, документация производителя, регистры или результаты измерений, если они есть
